### ISSUE TITLE
Small errors to fix

### ISSUE THREAD

**Issue by MrExo3D** [nionio6915/Euclid_Probe#10]
RRF3_Example_Auto_Deploy_Probe_Fixed_Dock.g

Line 104
G0 X150 Y150 G3000            ; move to the center of the bed

G3000 should be F3000

---------------------------------
RRF3_Example_Auto_Retract_Probe_Fixed_Dock.g

Line 68
G0 X0 Y70 F3000               ; move to ready position

Should be updated to be

G0 X0 Y70 F3000               ; move to Dock Re-entry staging  position

**Comment by nionio6915** [comment]
thank you.
