### ISSUE TITLE
Voron CAD models missing body.

### ISSUE THREAD

**Issue by GiulianoM** [nionio6915/Euclid_Probe#3]
The Voron 2.4 mount files under /CAD/Voron are missing the actual body for the mount.

All that are in the files are the extrusions and screws.

Please re-upload the files with the mount bodies included.

**Comment by nionio6915** [comment]
i will look and regenerate. 
thanks for letting me know

**Comment by nionio6915** [comment]
I uploaded all the parts in 1 file as dxf. 
You should be able to import into any CAD program.
