### ISSUE TITLE
Supply STEP files

### ISSUE THREAD

**Issue by adsaxton** [nionio6915/Euclid_Probe#4]
I'm trying to customize mounting, but your STLs won't convert to solid well. Would it be possible to supply STEP files as well? I'd be happy to share my results with you.

**Comment by nionio6915** [comment]
There are a bunch of .stp's in the CAD folder. 

Which ones do you you need if they are not there? 

Fastest way to figure it out would be on discord, jump on over there.

**Comment by adsaxton** [comment]
Thanks. I have since found them. I would like the stp of the M3 variant of the BLTouch mount.
