### ISSUE TITLE
Which gantry mount (Voron 2.4) is recommended?

### ISSUE THREAD

**Issue by alexvonsiebenthal** [nionio6915/Euclid_Probe#5]
I want to replace my Voron's Z endstop pin with the euclid probe. I suppose, I'll need to mount the dock to the gantry - is that correct?
If so, which of the numerous gantry mounts is the one recommended by the Euclid team?

![image](https://user-images.githubusercontent.com/6860125/156851943-52848a93-66a4-426c-8fe7-5eb6c6bd6435.png)

Thank you!

**Comment by nionio6915** [comment]
The dock can live either on the bedrail or the gantry. Recommend leaving the Z-endstop and use the bed rail dock mount. 

If gantry, its dependant on which orientation you want the probe to 'point'  and your firmware macros. 
If you are wanting to maitain the klicky macros, use the straight arm. 
If you want more secure- use the 90 degree mount. 
 
We just updated the Voron pages in attempt to clarify more. 
https://euclidprobe.github.io/02c_Voron.html

Discord discussion is always the fasted response.
