### ISSUE TITLE
soldering_jigV5-0.2mm_margin.stl has broken vertices on top layer

### ISSUE THREAD

**Issue by martinw89** [nionio6915/Euclid_Probe#8]
![image](https://user-images.githubusercontent.com/403999/171528346-9a6399bf-2451-4c83-bc0a-b60cf0d28a53.png)
![image](https://user-images.githubusercontent.com/403999/171528617-1ca85437-2d1a-4fff-9857-ad9c3eac7adc.png)

There appears to be some broken vertices in the current 0.2mm version of the jig. These are not present on the 0.3mm version. Visible in the github STL previewer, so I don't think it's a local problem with my slicer

**Comment by nionio6915** [comment]
thanks for letting us know. 
we fixed them in the 0.2mm and checked/fixed the rest too.
